define([], function() {
  return {
    BasicGroupName: "Basic Settings",
    BreadcrumbLoading: "Loading...",
    BreadcrumbStart: "Start",
    centimeters: "centimeters",
    Edit: "Edit",
    Error: "Error",
    FieldConfigureLabel: "Configure",
    FieldEnableNavHeader: "Display Navigation Path",
    FieldEnableNavigation: "Enable Single-Click Navigation",
    FieldForceOpenOfficeFiles: "Force Open Office Files",
    FieldHeight: "Diagram height",
    FieldHeightDescription: "Specify height value and units",
    FieldHyperlinksNewWindow: "Open Hyperlinks in New Window",
    FieldStartPage: "Initial Page",
    FieldStartPageDescription: "Page (name) to activate on load",
    FieldVisioFile: "Visio File",
    FieldVisioFileBrowse: "Browse...",
    FieldWidth: "Diagram width",
    FieldWidthDescription: "Specify width value and units",
    FieldZoom: "Default Zoom (%)",
    FieldZoomDescription: "Zoom level (percents) to set on load",
    inches: "inches",
    messageArePermissionsMissing: "Are some permissions missing?",
    messageCannotResolveFileURL: "Cannot resolve file URL:",
    messageSomethingWentWrongResolveURL: "Something went wrong when resolving file URL:",
    messageVisioFileCannotAccessed: "The Visio file this web part is connected to cannot be accessed at the URL",
    messageVisioFileNotFound: "The Visio file this web part is connected to is not found at the URL",
    messageWasTheFileDeleted: "Was the file deleted?",
    millimeters: "millimeters",
    NavigationHome: "Home",
    percOfFrame: "% of the frame",
    percOfScreen: "% of the screen",
    pixels: "pixels",
    placeholderIconTextPleaseclickBrowse: "Please click 'Browse...' Button on configuration panel to select the diagram.",
    placeholderIconTextPleaseclickConfigure: "Click 'Configure' button to reconfigure this web part.",
    placeholderIconTextPleaseclickEdit: "Please click 'Edit' to start page editing to reconfigure this web part.",
    placeholderIconTextPleaseclickSettings: "Please click 'Settings' menu on the Tab to reconfigure this web part.",
    placeholderIconTextUnableShowVisio: "Unable to show this Visio diagram",
    placeholderIconTextVisioNotSelected: "Visio diagram not selected",
    points: "points",
    PropertyPaneLabelAbout: "About",
    PropertyPaneLabelAppearance: "Appearance",
    PropertyPaneLabeldisableHyperlinks: "Disable Hyperlinks",
    PropertyPaneLabeldisablePan: "Disable Pan",
    PropertyPaneLabeldisablePanZoomWindow: "Disable PanZoom Window",
    PropertyPaneLabeldisableZoom: "Disable Zoom",
    PropertyPaneLabelDrawingDisplay: "Drawing Display",
    PropertyPaneLabelhideBorders: "Hide Borders",
    PropertyPaneLabelhideDiagramBoundary: "Hide Diagram Boundary",
    PropertyPaneLabelhideToolbars: "Hide Toolbars",
    PropertyPaneLabelInteractivity: "Drawing Interactivity",
    UploadTo: "Upload To",
    UrlNotSelected: "Not selected",
    UrlPickerBrowse: "Browse...",
    View: "View",
    VisioDocument: "Visio Document"
  };
});